Registration page
gcxchange-gcechange/react-landing-page pull request #5
Opened 2021-08-03 16:13 UTC by piet0024

Modified the landing page to a registration form.

2021-08-04 13:11 UTC, Steph4104 requested changes
When I enter my email the register button switch to enable but the department field is empty. I did the testing in edge.

Is it possible to have the department dropdown in alphabetical order for french and english.

2021-08-04 13:11 UTC, Steph4104 commented on src/pages/ProcessEn.js
> +      <p>If you don't receive an email after 10 minutes, please contact us at <a href="mailto:support-soutien@gcx-gce.gc.ca.">support-soutien@gcx-gce.gc.ca. </a></p>
remove the . in the href mailto

2021-08-04 13:11 UTC, Steph4104 commented on src/pages/ProcessFr.js
> +      <p>Si vous ne recevez pas de courriel après 10 minutes, veuillez communiquer avec nous à l’adresse suivante : <a href="mailto:support-soutien@gcx-gce.gc.ca.">support-soutien@gcx-gce.gc.ca.</a><
remove the . in the href mailto

2021-08-04 13:11 UTC, Steph4104 commented on src/i18n/lang.js
> +            emailPlaceholder: 'john.smith@tbs-sct.gc.ca, john.smith@ssc-spc.gc.ca, etc',
Remove etc

2021-08-04 13:11 UTC, Steph4104 commented on src/i18n/lang.js
> +            emailPlaceholder: 'jeanne.tremblay@tbs-sct.gc.ca, jeanne.tremblay@ssc-spc.gc.ca, etc.',
Remove etc

2021-08-05 15:24 UTC, Phanoix approved these changes

2021-08-11 15:40 UTC, ethanWallace approved these changes

2021-08-11 18:48 UTC, merged